package main

import (
	"os"
	"path/filepath"
	"testing"
)

// syntheticHeader is a minimal CGO-style header with a mix of valid (ad_*)
// and invalid (non-prefixed) function declarations, CGO runtime helpers
// (_GoStringLen, _GoStringPtr), and non-declaration lines that must be ignored.
const syntheticHeader = `/* Code generated by cmd/cgo; DO NOT EDIT. */

#include <stdint.h>

typedef struct { const char *p; ptrdiff_t n; } GoString;
typedef struct { void *data; GoInt len; cap; } GoSlice;

extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);

extern char* ad_open(char* p0);
extern char* ad_close(char* p0);
extern void  ad_free_cstring(char* p0);
extern char* bad_verb(char* p0);
extern char* also_bad(char* p0);
`

// syntheticHeaderClean has only ad_-prefixed declarations.
const syntheticHeaderClean = `/* Code generated by cmd/cgo; DO NOT EDIT. */

extern char* ad_kill(char* p0);
extern char* ad_status(char* p0);
extern void  ad_free_cstring(char* p0);
`

func writeTempHeader(t *testing.T, content string) string {
	t.Helper()
	dir := t.TempDir()
	path := filepath.Join(dir, "test.h")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write temp header: %v", err)
	}
	return path
}

func TestCheckHeaderViolations(t *testing.T) {
	path := writeTempHeader(t, syntheticHeader)
	violations, err := checkHeader(path)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(violations) != 2 {
		t.Fatalf("want 2 violations, got %d: %v", len(violations), violations)
	}
	want := map[string]bool{"bad_verb": true, "also_bad": true}
	for _, v := range violations {
		if !want[v] {
			t.Errorf("unexpected violation %q", v)
		}
	}
}

func TestCheckHeaderClean(t *testing.T) {
	path := writeTempHeader(t, syntheticHeaderClean)
	violations, err := checkHeader(path)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(violations) != 0 {
		t.Fatalf("want 0 violations, got %d: %v", len(violations), violations)
	}
}

func TestCheckHeaderMissing(t *testing.T) {
	_, err := checkHeader("/nonexistent/path/header.h")
	if err == nil {
		t.Fatal("expected error for missing file, got nil")
	}
}

func TestExtractFuncName(t *testing.T) {
	cases := []struct {
		line    string
		wantOK  bool
		wantName string
	}{
		{"extern char* ad_open(char* p0);", true, "ad_open"},
		{"extern void ad_free_cstring(char* p0);", true, "ad_free_cstring"},
		{"extern GoString ad_status(GoString p0);", true, "ad_status"},
		{"extern char* bad_verb(char* p0);", true, "bad_verb"},
		// CGO runtime helpers — underscore-prefixed, must be skipped.
		{"extern size_t _GoStringLen(_GoString_ s);", false, ""},
		{"extern const char *_GoStringPtr(_GoString_ s);", false, ""},
		{"typedef struct { int x; } Foo;", false, ""},
		{"/* a comment */", false, ""},
		{"#include <stdint.h>", false, ""},
		{"extern char*  spaced_ptr  (char* p0);", true, "spaced_ptr"},
	}
	for _, tc := range cases {
		name, ok := extractFuncName(tc.line)
		if ok != tc.wantOK {
			t.Errorf("extractFuncName(%q): ok=%v, want %v", tc.line, ok, tc.wantOK)
			continue
		}
		if ok && name != tc.wantName {
			t.Errorf("extractFuncName(%q): name=%q, want %q", tc.line, name, tc.wantName)
		}
	}
}
