/**
 * public-surface.test.ts — Epic C / SR-10.6.
 *
 * Type-level diff against checked-in golden snapshots of the published
 * declaration files. Picks the snapshot mechanism per SRD Open Tech
 * Question #3 (the simpler option of the two listed).
 *
 * Files under guard:
 *   dist/index.d.ts   — the public re-export barrel.
 *   dist/errors.d.ts  — declarations for AgentDirectorError + every Err*.
 *   dist/types.d.ts   — declarations for ClientOptions + verb Params/Result.
 *
 * Goldens live at `test/fixtures/public-surface/<file>.golden`. They are
 * regenerated by running `bun run build && bun run scripts/update-surface-golden.ts`.
 *
 * Behaviour:
 *   - The test first invokes `tsc --emitDeclarationOnly` so the comparison
 *     uses freshly-emitted .d.ts files rather than stale ones from a prior
 *     build. The Bun.spawnSync call is synchronous; the recipe is cheap
 *     (a few seconds) on this small package.
 *   - Any deliberate breaking change to a pre-existing exported type
 *     produces a non-empty diff and fails the test. Additive new exports
 *     also produce a diff; the operator updates the golden file and
 *     reviews the diff to confirm the change is purely additive (the
 *     PRD's byte-identical-surface acceptance criterion).
 */

import { test, expect, beforeAll } from "bun:test";
import * as path from "path";
import * as fs from "fs";
import { Client } from "../src/client.js";

const pkgRoot = path.resolve(import.meta.dir, "..");
const fixtureDir = path.join(pkgRoot, "test", "fixtures", "public-surface");
const distDir = path.join(pkgRoot, "dist");
const tscBin = path.join(pkgRoot, "node_modules", ".bin", "tsc");

const TRACKED = ["index.d.ts", "errors.d.ts", "types.d.ts"] as const;

beforeAll(() => {
  // Regenerate .d.ts files. The Bun.build phase produces .js; tsc produces
  // .d.ts. We only need the declaration files for this test.
  if (!fs.existsSync(tscBin)) {
    throw new Error(
      `public-surface: tsc not found at ${tscBin}; run 'bun install' first`
    );
  }
  const proc = Bun.spawnSync({
    cmd: [tscBin, "--emitDeclarationOnly"],
    cwd: pkgRoot,
    stdout: "pipe",
    stderr: "pipe",
  });
  if (proc.exitCode !== 0) {
    const stderr = new TextDecoder().decode(proc.stderr);
    const stdout = new TextDecoder().decode(proc.stdout);
    throw new Error(
      `public-surface: tsc --emitDeclarationOnly failed (exit ${proc.exitCode})\nstdout: ${stdout}\nstderr: ${stderr}`
    );
  }
});

test.each([...TRACKED])(
  "public-surface: dist/%s matches golden (SR-10.6)",
  (filename) => {
    const actualPath = path.join(distDir, filename);
    const goldenPath = path.join(fixtureDir, `${filename}.golden`);

    if (!fs.existsSync(goldenPath)) {
      throw new Error(
        `public-surface: golden file missing: ${goldenPath}\n` +
          `Regenerate with: bun run build && bun run scripts/update-surface-golden.ts`
      );
    }
    if (!fs.existsSync(actualPath)) {
      throw new Error(
        `public-surface: dist file missing: ${actualPath}\n` +
          `tsc emit failed silently or rootDir misconfigured`
      );
    }

    const actual = fs.readFileSync(actualPath, "utf-8");
    const expected = fs.readFileSync(goldenPath, "utf-8");

    // Direct byte equality. Mismatch indicates either an additive change
    // (regenerate the golden after confirming the change is purely
    // additive) or a deliberate-or-accidental break to a pre-existing
    // export (fix the source or roll the change back).
    expect(actual).toBe(expected);
  }
);

test("public-surface: golden tracks all three TRACKED files", () => {
  for (const f of TRACKED) {
    const goldenPath = path.join(fixtureDir, `${f}.golden`);
    expect(fs.existsSync(goldenPath)).toBe(true);
  }
});

test("public-surface: Client exposes no migrate method (SR-1)", () => {
  // SR-1 negative invariant: the schema-migration gate is a Go-side,
  // refuse-and-instruct mechanism. It has NO catalog entry, NO TS error
  // class, and crucially NO npm-client trigger. The published Client must
  // therefore expose nothing a caller could invoke to request a migration.
  //
  // This assertion walks the *runtime* prototype chain of the exported
  // Client class rather than the .d.ts goldens, so it holds independently
  // of golden regeneration: even if someone regenerates the surface goldens
  // after accidentally adding a migrate verb, this test still fails.
  const forbidden = ["migrate", "migrateSchema", "runMigration", "schemaMigrate"];

  const seen = new Set<string>();
  for (
    let proto: object | null = Client.prototype;
    proto && proto !== Object.prototype;
    proto = Object.getPrototypeOf(proto)
  ) {
    for (const key of Object.getOwnPropertyNames(proto)) {
      seen.add(key);
    }
  }

  for (const name of forbidden) {
    expect(
      seen.has(name),
      `Client (or a base class) unexpectedly exposes a "${name}" method; ` +
        `SR-1 forbids any npm-client migration trigger.`
    ).toBe(false);
  }

  // Defence in depth: no enumerable method on the runtime surface may even
  // contain the substring "migrat" (catches migrateFoo / fooMigrate drift).
  const migratLike = [...seen].filter((k) => /migrat/i.test(k));
  expect(
    migratLike.length === 0,
    `Client runtime surface contains migration-shaped method(s): ${migratLike.join(", ")}`
  ).toBe(true);

  // The tracked .d.ts goldens must also stay migration-free. This part is
  // golden-derived (informational), but the runtime checks above are the
  // load-bearing, regeneration-proof guarantee.
  for (const f of TRACKED) {
    const golden = fs.readFileSync(path.join(fixtureDir, `${f}.golden`), "utf-8");
    expect(golden).not.toMatch(/migrat/i);
  }
});

test("public-surface: dist/index.d.ts does not leak _cliPath (SR-4.9)", () => {
  // The SR-4.1 fence: `_cliPath` is a covert DI hatch on the runtime
  // ClientOptions object but is NOT typed on the public interface.  This
  // assertion guards against a future refactor that accidentally widens
  // ClientOptions (or any other exported interface) to expose the field.
  const distIndexDts = path.join(distDir, "index.d.ts");
  const src = fs.readFileSync(distIndexDts, "utf-8");
  expect(src).not.toContain("_cliPath");
});
