/**
 * public-surface.test.ts — Epic C / SR-10.6.
 *
 * Type-level diff against checked-in golden snapshots of the published
 * declaration files. Picks the snapshot mechanism per SRD Open Tech
 * Question #3 (the simpler option of the two listed).
 *
 * Files under guard:
 *   dist/index.d.ts   — the public re-export barrel.
 *   dist/errors.d.ts  — declarations for AgentDirectorError + every Err*.
 *   dist/types.d.ts   — declarations for ClientOptions + verb Params/Result.
 *
 * Goldens live at `test/fixtures/public-surface/<file>.golden`. They are
 * regenerated by running `bun run build && bun run scripts/update-surface-golden.ts`.
 *
 * Behaviour:
 *   - The test first invokes `tsc --emitDeclarationOnly` so the comparison
 *     uses freshly-emitted .d.ts files rather than stale ones from a prior
 *     build. The Bun.spawnSync call is synchronous; the recipe is cheap
 *     (a few seconds) on this small package.
 *   - Any deliberate breaking change to a pre-existing exported type
 *     produces a non-empty diff and fails the test. Additive new exports
 *     also produce a diff; the operator updates the golden file and
 *     reviews the diff to confirm the change is purely additive (the
 *     PRD's byte-identical-surface acceptance criterion).
 */

import { test, expect, beforeAll } from "bun:test";
import * as path from "path";
import * as fs from "fs";

const pkgRoot = path.resolve(import.meta.dir, "..");
const fixtureDir = path.join(pkgRoot, "test", "fixtures", "public-surface");
const distDir = path.join(pkgRoot, "dist");
const tscBin = path.join(pkgRoot, "node_modules", ".bin", "tsc");

const TRACKED = ["index.d.ts", "errors.d.ts", "types.d.ts"] as const;

beforeAll(() => {
  // Regenerate .d.ts files. The Bun.build phase produces .js; tsc produces
  // .d.ts. We only need the declaration files for this test.
  if (!fs.existsSync(tscBin)) {
    throw new Error(
      `public-surface: tsc not found at ${tscBin}; run 'bun install' first`
    );
  }
  const proc = Bun.spawnSync({
    cmd: [tscBin, "--emitDeclarationOnly"],
    cwd: pkgRoot,
    stdout: "pipe",
    stderr: "pipe",
  });
  if (proc.exitCode !== 0) {
    const stderr = new TextDecoder().decode(proc.stderr);
    const stdout = new TextDecoder().decode(proc.stdout);
    throw new Error(
      `public-surface: tsc --emitDeclarationOnly failed (exit ${proc.exitCode})\nstdout: ${stdout}\nstderr: ${stderr}`
    );
  }
});

test.each([...TRACKED])(
  "public-surface: dist/%s matches golden (SR-10.6)",
  (filename) => {
    const actualPath = path.join(distDir, filename);
    const goldenPath = path.join(fixtureDir, `${filename}.golden`);

    if (!fs.existsSync(goldenPath)) {
      throw new Error(
        `public-surface: golden file missing: ${goldenPath}\n` +
          `Regenerate with: bun run build && bun run scripts/update-surface-golden.ts`
      );
    }
    if (!fs.existsSync(actualPath)) {
      throw new Error(
        `public-surface: dist file missing: ${actualPath}\n` +
          `tsc emit failed silently or rootDir misconfigured`
      );
    }

    const actual = fs.readFileSync(actualPath, "utf-8");
    const expected = fs.readFileSync(goldenPath, "utf-8");

    // Direct byte equality. Mismatch indicates either an additive change
    // (regenerate the golden after confirming the change is purely
    // additive) or a deliberate-or-accidental break to a pre-existing
    // export (fix the source or roll the change back).
    expect(actual).toBe(expected);
  }
);

test("public-surface: golden tracks all three TRACKED files", () => {
  for (const f of TRACKED) {
    const goldenPath = path.join(fixtureDir, `${f}.golden`);
    expect(fs.existsSync(goldenPath)).toBe(true);
  }
});
