/**
 * readme-snippets.test.ts — compile-gate for README.md TS code blocks.
 *
 * Extracts every ```ts / ```typescript fenced block from README.md, wraps
 * them in an async function with a full preamble import, writes the result
 * to a temp file inside this directory, and asserts that
 * `tsc --noEmit ...` exits 0.
 *
 * If tsc fails the test prints the temp file path so you can inspect it.
 * This catches drift between the README examples and the actual API
 * signatures (renamed fields, removed exports, changed param shapes, etc.).
 */

import { test, expect } from "bun:test";
import * as fs from "fs";
import * as path from "path";

const PKG_DIR = path.resolve(import.meta.dir, "..");
const README_PATH = path.join(PKG_DIR, "README.md");
const TSC_BIN = path.join(PKG_DIR, "node_modules/.bin/tsc");

// ---------------------------------------------------------------------------
// Static preamble — imports every public export so snippets don't repeat them.
// noUnusedLocals is false in tsconfig.typecheck.json so unused imports are OK.
// ---------------------------------------------------------------------------
const PREAMBLE = `\
// Auto-generated by readme-snippets.test.ts — do not edit.
import {
  Client,
  AgentDirectorError,
  ErrClientClosed,
  ErrBunVersionTooOld,
  errorFromEnvelope,
  ErrCwdMissing,
  ErrCwdNotAPath,
  ErrCwdNotFound,
  ErrCwdNotADirectory,
  ErrRelayModeInvalid,
  ErrSpawnDeniedFlag,
  ErrReservedEnvKey,
  ErrInstanceIdCollision,
  ErrTmuxSessionNameEmpty,
  ErrTmuxSessionNameInvalid,
  ErrTmuxSessionNameTooLong,
  ErrSpawnNotFound,
  ErrTmuxNotAvailable,
  ErrTmuxSessionCreate,
  ErrTmuxSendKeys,
  ErrTmuxCaptureFailed,
  ErrSpawnNotInteractive,
  ErrSendKeysWhileRelayed,
  ErrSpawnNotPausable,
  ErrPauseTimeout,
  ErrListInvalidLabel,
  ErrTemplateNameUnsafe,
  ErrTemplateNotFound,
  ErrTemplateMalformed,
  ErrTemplateExists,
  ErrProbeUnsupported,
  ErrSpawnNotResumable,
  ErrNoSessionId,
  ErrJsonlMissing,
  ErrRelayModeOff,
  ErrInvalidDecision,
  ErrNoOpenPermissionRequest,
  ErrAlreadyDecided,
  MIN_BINARY_VERSION,
  DEV_SENTINEL_VERSION,
} from "../src/index.js";

// Placeholder for README snippets that reference an unbound symbol
// (e.g. the version-floor example that compares against a captured
// 'binaryVersion' value before the discovery surface lands in Epic 3).
declare const binaryVersion: string;
void binaryVersion;
`;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Extract every ```ts / ```typescript block from markdown. */
function extractTsBlocks(markdown: string): Array<{ code: string; index: number }> {
  const results: Array<{ code: string; index: number }> = [];
  const re = /```(?:ts|typescript)\n([\s\S]*?)```/g;
  let m: RegExpExecArray | null;
  let idx = 0;
  while ((m = re.exec(markdown)) !== null) {
    results.push({ code: m[1], index: idx++ });
  }
  return results;
}

/**
 * Strip top-level `import` statements from a snippet so the preamble's
 * static import handles all symbol resolution (avoids duplicate / unresolvable
 * imports from documentation-style examples that show the package name).
 */
function stripImports(code: string): string {
  return code
    .split("\n")
    .filter((line) => !line.trimStart().startsWith("import "))
    .join("\n");
}

/** Indent every line by `n` spaces. */
function indent(code: string, n: number): string {
  const pad = " ".repeat(n);
  return code
    .split("\n")
    .map((l) => (l.trim() === "" ? "" : pad + l))
    .join("\n");
}

// ---------------------------------------------------------------------------
// Test
// ---------------------------------------------------------------------------

test("README TS snippets typecheck", () => {
  // Read README.
  const readme = fs.readFileSync(README_PATH, "utf8");
  const blocks = extractTsBlocks(readme);
  expect(
    blocks.length,
    "README.md must contain at least one ```ts block"
  ).toBeGreaterThan(0);

  // Build the source: preamble + outer placeholder + each snippet in its own
  // block scope (avoids variable-name collisions across snippets).
  const snippetSections = blocks
    .map(
      ({ code, index }) =>
        `  // === README snippet ${index + 1} ===\n  {\n${indent(
          stripImports(code),
          4
        )}\n  }`
    )
    .join("\n");

  const fullSource = [
    PREAMBLE,
    "// eslint-disable-next-line @typescript-eslint/require-await",
    "async function _readme() {",
    "  // Placeholder client available to verb snippets that omit construction.",
    "  const client = null as unknown as Client;",
    "  void client;",
    "",
    snippetSections,
    "}",
    "void _readme;",
  ].join("\n");

  // Write to test/ so relative imports (../src/index.js) resolve correctly.
  const tmpFile = path.join(
    import.meta.dir,
    `tmp-readme-check-${Date.now()}.ts`
  );

  try {
    fs.writeFileSync(tmpFile, fullSource, "utf8");

    const result = Bun.spawnSync(
      [
        TSC_BIN,
        "--noEmit",
        "--ignoreConfig",
        "--strict",
        "--target",
        "ES2022",
        "--module",
        "ESNext",
        "--moduleResolution",
        "bundler",
        "--lib",
        "ES2022,ESNext.Disposable",
        "--types",
        "bun-types",
        "--skipLibCheck",
        tmpFile,
      ],
      { cwd: PKG_DIR }
    );

    if (result.exitCode !== 0) {
      const out = new TextDecoder().decode(result.stdout);
      const err = new TextDecoder().decode(result.stderr);
      const msg = [
        `README TS snippets failed typecheck (tsc exit ${result.exitCode}).`,
        `Inspect temp file: ${tmpFile}`,
        out ? `stdout:\n${out}` : "",
        err ? `stderr:\n${err}` : "",
      ]
        .filter(Boolean)
        .join("\n");
      // Keep temp file for inspection on failure.
      throw new Error(msg);
    }

    expect(result.exitCode).toBe(0);
  } finally {
    // Always clean up. On failure the error message above contains the temp
    // file path AND the tsc output, so the file is not needed for inspection.
    try {
      fs.unlinkSync(tmpFile);
    } catch {
      /* best-effort */
    }
  }
});
