package main

import "fmt"

// driftCheck reports whether the freshly generated bytes match the bytes
// currently on disk. It returns nil when they are byte-identical and an
// error naming the path otherwise — the error message is the contract the
// (future) drift helper script and tests rely on.
//
// CI itself uses `git diff --exit-code docs/` for the real drift gate; this
// helper documents the same byte-level contract in a unit-testable form.
func driftCheck(path, generated, onDisk string) error {
	if generated == onDisk {
		return nil
	}
	return fmt.Errorf("doc drift detected in %s: regenerate with 'make generate' and commit the result", path)
}
