package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/gabemahoney/agent-director/internal/api/manifest"
)

// TestGenerate_OutputContent runs generate against a tempdir-rooted fake
// repo and verifies each output file carries the expected per-format
// markers plus the help verb's manifest-sourced text.
func TestGenerate_OutputContent(t *testing.T) {
	tmp := t.TempDir()
	if err := os.MkdirAll(filepath.Join(tmp, "docs"), 0o755); err != nil {
		t.Fatalf("mkdir docs: %v", err)
	}
	if err := generate(tmp); err != nil {
		t.Fatalf("generate: %v", err)
	}

	helpVerb, ok := manifest.Lookup("help")
	if !ok {
		t.Fatal("manifest missing help verb (precondition)")
	}
	if len(helpVerb.ResultFields) == 0 {
		t.Fatal("help verb has no result fields (precondition)")
	}
	firstResultField := helpVerb.ResultFields[0].Name

	cases := []struct {
		name        string
		path        string
		uniqueMark  string
		extraNeeded []string
	}{
		{
			name:       "cli",
			path:       "cli-reference.md",
			uniqueMark: "### Parameters",
			extraNeeded: []string{
				"# CLI reference",
				"### Result",
				"### Errors",
			},
		},
		{
			name:       "mcp",
			path:       "mcp-reference.md",
			uniqueMark: "Tool:",
			extraNeeded: []string{
				"# MCP reference",
				"### Input schema",
				"### Output schema",
			},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			raw, err := os.ReadFile(filepath.Join(tmp, "docs", tc.path))
			if err != nil {
				t.Fatalf("read %s: %v", tc.path, err)
			}
			got := string(raw)

			// Header is the first content line.
			if !strings.HasPrefix(got, "<!-- This file is auto-generated by 'make generate'. Do not edit by hand. -->\n") {
				t.Errorf("%s: missing or misplaced do-not-edit header; got prefix %q", tc.path, firstLine(got))
			}
			// Single trailing newline.
			if !strings.HasSuffix(got, "\n") || strings.HasSuffix(got, "\n\n") {
				t.Errorf("%s: want exactly one trailing newline", tc.path)
			}

			mustContain(t, tc.path, got, "help")
			mustContain(t, tc.path, got, helpVerb.Description)
			mustContain(t, tc.path, got, firstResultField)
			mustContain(t, tc.path, got, tc.uniqueMark)
			for _, want := range tc.extraNeeded {
				mustContain(t, tc.path, got, want)
			}
		})
	}
}

// TestGenerate_Deterministic asserts byte-identical output across two runs
// against the same tempdir — the contract the CI drift gate relies on.
func TestGenerate_Deterministic(t *testing.T) {
	tmp := t.TempDir()
	if err := os.MkdirAll(filepath.Join(tmp, "docs"), 0o755); err != nil {
		t.Fatalf("mkdir docs: %v", err)
	}
	if err := generate(tmp); err != nil {
		t.Fatalf("generate#1: %v", err)
	}
	cli1, _ := os.ReadFile(filepath.Join(tmp, "docs", "cli-reference.md"))
	mcp1, _ := os.ReadFile(filepath.Join(tmp, "docs", "mcp-reference.md"))
	if err := generate(tmp); err != nil {
		t.Fatalf("generate#2: %v", err)
	}
	cli2, _ := os.ReadFile(filepath.Join(tmp, "docs", "cli-reference.md"))
	mcp2, _ := os.ReadFile(filepath.Join(tmp, "docs", "mcp-reference.md"))
	if string(cli1) != string(cli2) {
		t.Error("cli-reference.md not byte-identical across two runs")
	}
	if string(mcp1) != string(mcp2) {
		t.Error("mcp-reference.md not byte-identical across two runs")
	}
}

// TestGenerate_OverwritesManualEdit confirms that hand-edits to a tracked
// doc file are clobbered by the next generate run.
func TestGenerate_OverwritesManualEdit(t *testing.T) {
	tmp := t.TempDir()
	if err := os.MkdirAll(filepath.Join(tmp, "docs"), 0o755); err != nil {
		t.Fatalf("mkdir docs: %v", err)
	}
	path := filepath.Join(tmp, "docs", "cli-reference.md")
	if err := os.WriteFile(path, []byte("HAND EDITED CONTENT\n"), 0o644); err != nil {
		t.Fatalf("write stub: %v", err)
	}
	if err := generate(tmp); err != nil {
		t.Fatalf("generate: %v", err)
	}
	raw, _ := os.ReadFile(path)
	if strings.Contains(string(raw), "HAND EDITED CONTENT") {
		t.Error("generate did not overwrite hand-edited content")
	}
}

func mustContain(t *testing.T, label, haystack, needle string) {
	t.Helper()
	if !strings.Contains(haystack, needle) {
		t.Errorf("%s: missing expected substring %q", label, needle)
	}
}

func firstLine(s string) string {
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		return s[:i]
	}
	return s
}
