package main

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/gabemahoney/agent-director/internal/mcp"
	"github.com/gabemahoney/agent-director/pkg/api/manifest"
)

// TestGenerate_OutputContent runs generate against a tempdir-rooted fake
// repo and verifies each output file carries the expected per-format
// markers plus the help verb's manifest-sourced text.
func TestGenerate_OutputContent(t *testing.T) {
	tmp := t.TempDir()
	if err := os.MkdirAll(filepath.Join(tmp, "docs"), 0o755); err != nil {
		t.Fatalf("mkdir docs: %v", err)
	}
	if err := generate(tmp); err != nil {
		t.Fatalf("generate: %v", err)
	}

	helpVerb, ok := manifest.Lookup("help")
	if !ok {
		t.Fatal("manifest missing help verb (precondition)")
	}
	if len(helpVerb.ResultFields) == 0 {
		t.Fatal("help verb has no result fields (precondition)")
	}
	firstResultField := helpVerb.ResultFields[0].Name

	cases := []struct {
		name        string
		path        string
		uniqueMark  string
		extraNeeded []string
	}{
		{
			name:       "cli",
			path:       "cli-reference.md",
			uniqueMark: "### Parameters",
			extraNeeded: []string{
				"# CLI reference",
				"### Result",
				"### Errors",
			},
		},
		{
			name:       "mcp",
			path:       "mcp-reference.md",
			uniqueMark: "Tool:",
			extraNeeded: []string{
				"# MCP reference",
				"### Input schema",
				"### Output schema",
			},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			raw, err := os.ReadFile(filepath.Join(tmp, "docs", tc.path))
			if err != nil {
				t.Fatalf("read %s: %v", tc.path, err)
			}
			got := string(raw)

			// Header is the first content line.
			if !strings.HasPrefix(got, "<!-- This file is auto-generated by 'make generate'. Do not edit by hand. -->\n") {
				t.Errorf("%s: missing or misplaced do-not-edit header; got prefix %q", tc.path, firstLine(got))
			}
			// Single trailing newline.
			if !strings.HasSuffix(got, "\n") || strings.HasSuffix(got, "\n\n") {
				t.Errorf("%s: want exactly one trailing newline", tc.path)
			}

			mustContain(t, tc.path, got, "help")
			mustContain(t, tc.path, got, helpVerb.Description)
			mustContain(t, tc.path, got, firstResultField)
			mustContain(t, tc.path, got, tc.uniqueMark)
			for _, want := range tc.extraNeeded {
				mustContain(t, tc.path, got, want)
			}
		})
	}
}

// TestGenerate_MCPRespectsExposedVerb guards b.gk8: renderMCP must emit a
// tool section only for verbs mcp.ExposedVerb admits. Pre-fix, renderMCP
// walked every manifest verb, so mcp-reference.md documented hook, serve,
// and trail-emit as callable MCP tools even though the live server never
// registers them — this test's excluded-verb assertion would have failed.
func TestGenerate_MCPRespectsExposedVerb(t *testing.T) {
	tmp := t.TempDir()
	if err := os.MkdirAll(filepath.Join(tmp, "docs"), 0o755); err != nil {
		t.Fatalf("mkdir docs: %v", err)
	}
	if err := generate(tmp); err != nil {
		t.Fatalf("generate: %v", err)
	}
	raw, err := os.ReadFile(filepath.Join(tmp, "docs", "mcp-reference.md"))
	if err != nil {
		t.Fatalf("read mcp-reference.md: %v", err)
	}
	got := string(raw)

	// Every manifest verb: exposed → its Tool section must be present;
	// excluded (hook/serve/trail-emit) → it must be absent. Driving this
	// off manifest.Verbs + mcp.ExposedVerb keeps the assertion honest if
	// the exclusion set ever changes.
	sawExposed := false
	sawExcluded := false
	for _, v := range manifest.Verbs {
		section := "## Tool: " + v.Name + "\n"
		if mcp.ExposedVerb(v.Name) {
			sawExposed = true
			if !strings.Contains(got, section) {
				t.Errorf("mcp-reference.md missing tool section for exposed verb %q", v.Name)
			}
		} else {
			sawExcluded = true
			if strings.Contains(got, section) {
				t.Errorf("mcp-reference.md documents excluded verb %q as an MCP tool (ExposedVerb is false); renderMCP must skip it", v.Name)
			}
		}
	}
	if !sawExposed {
		t.Fatal("no exposed verbs in manifest (precondition)")
	}
	if !sawExcluded {
		t.Fatal("no excluded verbs in manifest — nothing for this regression to guard (precondition)")
	}
}

// retiredPendingConcepts matches the concepts SR-20.6 retires, in hyphen and
// space spellings (twin: pkg/api/manifest/pending_meaning_test.go).
var retiredPendingConcepts = regexp.MustCompile(`(?i)resume[-\s]?starting|young[-\s]claim|launched[-\s]mark|claim[-\s]withdrawal`)

// TestGenerate_PendingMeaning checks each generated reference renders the
// manifest's pending texts and names no retired concept (SR-20.6, AC-DOC-17).
func TestGenerate_PendingMeaning(t *testing.T) {
	tmp := t.TempDir()
	if err := os.MkdirAll(filepath.Join(tmp, "docs"), 0o755); err != nil {
		t.Fatalf("mkdir docs: %v", err)
	}
	if err := generate(tmp); err != nil {
		t.Fatalf("generate: %v", err)
	}

	status, ok := manifest.Lookup("status")
	if !ok {
		t.Fatal("manifest missing status verb (precondition)")
	}
	spawn, ok := manifest.Lookup("spawn")
	if !ok {
		t.Fatal("manifest missing spawn verb (precondition)")
	}
	var stateText string
	for _, f := range status.ResultFields {
		if f.Name == "state" {
			stateText = f.Description
		}
	}
	if !strings.Contains(stateText, "has not reported in") {
		t.Fatalf("status state text does not define pending (precondition): %q", stateText)
	}
	wants := []string{status.Description, stateText, spawn.Description}

	for _, name := range []string{"cli-reference.md", "mcp-reference.md"} {
		t.Run(name, func(t *testing.T) {
			raw, err := os.ReadFile(filepath.Join(tmp, "docs", name))
			if err != nil {
				t.Fatalf("read %s: %v", name, err)
			}
			got := string(raw)
			for _, want := range wants {
				mustContain(t, name, got, want)
			}
			for i, line := range strings.Split(got, "\n") {
				if m := retiredPendingConcepts.FindString(line); m != "" {
					t.Errorf("%s:%d names retired concept %q: %s", name, i+1, m, line)
				}
			}
		})
	}
}

// killOptIn matches kill's operator-only finished-row opt-in in any spelling
// (include-finished, include_finished, IncludeFinished, ...).
var killOptIn = regexp.MustCompile(`(?i)include.?finished`)

// TestGenerate_KillOptInAbsent: neither generated nor committed reference names
// the kill opt-in (SR-6.8), and each still documents kill with kill_sent.
func TestGenerate_KillOptInAbsent(t *testing.T) {
	tmp := t.TempDir()
	if err := os.MkdirAll(filepath.Join(tmp, "docs"), 0o755); err != nil {
		t.Fatalf("mkdir docs: %v", err)
	}
	if err := generate(tmp); err != nil {
		t.Fatalf("generate: %v", err)
	}
	sections := map[string]string{"cli-reference.md": "## kill\n", "mcp-reference.md": "## Tool: kill\n"}
	for _, dir := range []string{filepath.Join(tmp, "docs"), filepath.Join("..", "..", "docs")} {
		for name, heading := range sections {
			path := filepath.Join(dir, name)
			t.Run(path, func(t *testing.T) {
				raw, err := os.ReadFile(path)
				if err != nil {
					t.Fatalf("read %s: %v", path, err)
				}
				got := string(raw)
				for i, line := range strings.Split(got, "\n") {
					if m := killOptIn.FindString(line); m != "" {
						t.Errorf("SR-6.8: %s:%d names the operator-only kill opt-in %q: %s", path, i+1, m, line)
					}
				}
				_, section, ok := strings.Cut(got, heading)
				if !ok {
					t.Fatalf("%s has no %q section; the SR-6.8 absence check would pass vacuously", path, strings.TrimSpace(heading))
				}
				section, _, _ = strings.Cut(section, "\n## ")
				mustContain(t, path+" kill section", section, "kill_sent")
			})
		}
	}
}

// TestGenerate_Deterministic asserts byte-identical output across two runs
// against the same tempdir — the contract the CI drift gate relies on.
func TestGenerate_Deterministic(t *testing.T) {
	tmp := t.TempDir()
	if err := os.MkdirAll(filepath.Join(tmp, "docs"), 0o755); err != nil {
		t.Fatalf("mkdir docs: %v", err)
	}
	if err := generate(tmp); err != nil {
		t.Fatalf("generate#1: %v", err)
	}
	cli1, _ := os.ReadFile(filepath.Join(tmp, "docs", "cli-reference.md"))
	mcp1, _ := os.ReadFile(filepath.Join(tmp, "docs", "mcp-reference.md"))
	if err := generate(tmp); err != nil {
		t.Fatalf("generate#2: %v", err)
	}
	cli2, _ := os.ReadFile(filepath.Join(tmp, "docs", "cli-reference.md"))
	mcp2, _ := os.ReadFile(filepath.Join(tmp, "docs", "mcp-reference.md"))
	if string(cli1) != string(cli2) {
		t.Error("cli-reference.md not byte-identical across two runs")
	}
	if string(mcp1) != string(mcp2) {
		t.Error("mcp-reference.md not byte-identical across two runs")
	}
}

// TestGenerate_OverwritesManualEdit confirms that hand-edits to a tracked
// doc file are clobbered by the next generate run.
func TestGenerate_OverwritesManualEdit(t *testing.T) {
	tmp := t.TempDir()
	if err := os.MkdirAll(filepath.Join(tmp, "docs"), 0o755); err != nil {
		t.Fatalf("mkdir docs: %v", err)
	}
	path := filepath.Join(tmp, "docs", "cli-reference.md")
	if err := os.WriteFile(path, []byte("HAND EDITED CONTENT\n"), 0o644); err != nil {
		t.Fatalf("write stub: %v", err)
	}
	if err := generate(tmp); err != nil {
		t.Fatalf("generate: %v", err)
	}
	raw, _ := os.ReadFile(path)
	if strings.Contains(string(raw), "HAND EDITED CONTENT") {
		t.Error("generate did not overwrite hand-edited content")
	}
}

func mustContain(t *testing.T, label, haystack, needle string) {
	t.Helper()
	if !strings.Contains(haystack, needle) {
		t.Errorf("%s: missing expected substring %q", label, needle)
	}
}

func firstLine(s string) string {
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		return s[:i]
	}
	return s
}
