// Command gen-docs regenerates docs/cli-reference.md and docs/mcp-reference.md
// from the canonical verb manifest in pkg/api/manifest.
//
// Invoked by:
//
//	go generate ./...
//
// triggered by a //go:generate directive inside the manifest package. The
// directive runs with CWD = pkg/api/manifest, so this tool walks up
// the directory tree until it finds a go.mod and treats that directory as
// the repo root.
//
// Output is deterministic: no timestamps, no environment-dependent strings,
// LF line endings, single trailing newline. Two consecutive runs produce
// byte-identical files; the CI doc-drift gate (.github/workflows/doc-drift.yml)
// runs this generator and fails on any diff against tracked output.
package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"

	"github.com/gabemahoney/agent-director/pkg/api/manifest"
)

// genHeader is the first content line of every generated doc file. It
// signals to humans that hand-edits will be clobbered by `make generate`.
const genHeader = "<!-- This file is auto-generated by 'make generate'. Do not edit by hand. -->"

func main() {
	root, err := findRepoRoot()
	if err != nil {
		fmt.Fprintln(os.Stderr, "gen-docs:", err)
		os.Exit(1)
	}
	if err := generate(root); err != nil {
		fmt.Fprintln(os.Stderr, "gen-docs:", err)
		os.Exit(1)
	}
}

// generate writes docs/cli-reference.md and docs/mcp-reference.md under
// rootDir. rootDir must contain a docs/ subdirectory (the function creates
// it if missing). Exposed for tests.
func generate(rootDir string) error {
	docsDir := filepath.Join(rootDir, "docs")
	if err := os.MkdirAll(docsDir, 0o755); err != nil {
		return fmt.Errorf("mkdir docs: %w", err)
	}
	cli := renderCLI(manifest.Verbs)
	mcp := renderMCP(manifest.Verbs)
	if err := writeAtomic(filepath.Join(docsDir, "cli-reference.md"), cli); err != nil {
		return err
	}
	if err := writeAtomic(filepath.Join(docsDir, "mcp-reference.md"), mcp); err != nil {
		return err
	}
	return nil
}

// findRepoRoot walks up from CWD until it finds a directory containing
// go.mod and returns its absolute path.
func findRepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("getwd: %w", err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("no go.mod found walking up from CWD")
		}
		dir = parent
	}
}

// writeAtomic writes data to path via a tempfile + os.Rename so a crash
// mid-write never leaves a half-written tracked doc.
func writeAtomic(path string, data []byte) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".gen-docs-*")
	if err != nil {
		return fmt.Errorf("tempfile in %s: %w", dir, err)
	}
	tmpName := tmp.Name()
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		os.Remove(tmpName)
		return fmt.Errorf("write %s: %w", tmpName, err)
	}
	if err := tmp.Close(); err != nil {
		os.Remove(tmpName)
		return fmt.Errorf("close %s: %w", tmpName, err)
	}
	if err := os.Chmod(tmpName, 0o644); err != nil {
		os.Remove(tmpName)
		return fmt.Errorf("chmod %s: %w", tmpName, err)
	}
	if err := os.Rename(tmpName, path); err != nil {
		os.Remove(tmpName)
		return fmt.Errorf("rename %s -> %s: %w", tmpName, path, err)
	}
	return nil
}

// renderCLI emits human-reference markdown: per-verb description plus
// Parameters/Result/Errors subsections.
func renderCLI(verbs []manifest.VerbDef) []byte {
	var b bytes.Buffer
	fmt.Fprintln(&b, genHeader)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "# CLI reference")
	for _, v := range verbs {
		fmt.Fprintln(&b)
		fmt.Fprintf(&b, "## %s\n", v.Name)
		fmt.Fprintln(&b)
		fmt.Fprintln(&b, v.Description)
		fmt.Fprintln(&b)
		fmt.Fprintln(&b, "### Parameters")
		fmt.Fprintln(&b)
		if len(v.Params) == 0 {
			fmt.Fprintln(&b, "_None._")
		} else {
			for _, p := range v.Params {
				req := "optional"
				if p.Required {
					req = "required"
				}
				fmt.Fprintf(&b, "- `%s` (%s, %s): %s\n", p.Name, p.Type, req, p.Description)
			}
		}
		fmt.Fprintln(&b)
		fmt.Fprintln(&b, "### Result")
		fmt.Fprintln(&b)
		if len(v.ResultFields) == 0 {
			fmt.Fprintln(&b, "_None._")
		} else {
			for _, f := range v.ResultFields {
				fmt.Fprintf(&b, "- `%s` (%s): %s\n", f.Name, f.Type, f.Description)
			}
		}
		fmt.Fprintln(&b)
		fmt.Fprintln(&b, "### Errors")
		fmt.Fprintln(&b)
		if len(v.ErrorNames) == 0 {
			fmt.Fprintln(&b, "_None._")
		} else {
			for _, e := range v.ErrorNames {
				fmt.Fprintf(&b, "- `%s`\n", e)
			}
		}
	}
	return b.Bytes()
}

// renderMCP emits tool-schema-style markdown: per-verb Input schema, Output
// schema, and Errors subsections, framed so a reader can distinguish it at
// a glance from the CLI reference.
func renderMCP(verbs []manifest.VerbDef) []byte {
	var b bytes.Buffer
	fmt.Fprintln(&b, genHeader)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "# MCP reference")
	for _, v := range verbs {
		fmt.Fprintln(&b)
		fmt.Fprintf(&b, "## Tool: %s\n", v.Name)
		fmt.Fprintln(&b)
		fmt.Fprintln(&b, v.Description)
		fmt.Fprintln(&b)
		fmt.Fprintln(&b, "### Input schema")
		fmt.Fprintln(&b)
		if len(v.Params) == 0 {
			fmt.Fprintln(&b, "- (no input fields)")
		} else {
			for _, p := range v.Params {
				fmt.Fprintf(&b, "- `%s`: type=%s, required=%t — %s\n", p.Name, p.Type, p.Required, p.Description)
			}
		}
		fmt.Fprintln(&b)
		fmt.Fprintln(&b, "### Output schema")
		fmt.Fprintln(&b)
		if len(v.ResultFields) == 0 {
			fmt.Fprintln(&b, "- (no output fields)")
		} else {
			for _, f := range v.ResultFields {
				fmt.Fprintf(&b, "- `%s`: type=%s — %s\n", f.Name, f.Type, f.Description)
			}
		}
		fmt.Fprintln(&b)
		fmt.Fprintln(&b, "### Errors")
		fmt.Fprintln(&b)
		if len(v.ErrorNames) == 0 {
			fmt.Fprintln(&b, "- (none)")
		} else {
			for _, e := range v.ErrorNames {
				fmt.Fprintf(&b, "- `%s`\n", e)
			}
		}
	}
	return b.Bytes()
}
